language: node_js
node_js:
 - "node"
install:
 - npm ci

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "adn53"
      - git config --local user.email "adn53@drexel.edu"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
 provider: pages
 api_key: "dcef28793851140401cc50b4d81583e56fb0750f"
 on: 
   branch: gh-pages
 skip_cleanup: true
