language: node_js
node_js:
 - "node"
before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "adn53"
      - git config --local user.email "adn53@drexel.edu"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
deploy:
 provider: pages
 github_token: 
  secure: 5bf58df9a9a6bad438977b951aee21d3f21c44a07
 on: 
   branch: master
 skip_cleanup: true
